services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: eveilia-web
    ports:
      - "${APP_PORT}:80"
    environment:
      # Expose DB settings to PHP (if the app/installer reads env)
      DB_HOST: db
      DB_PORT: "${MYSQL_PORT}"
      DB_NAME: "${MYSQL_DATABASE}"
      DB_USER: "${MYSQL_USER}"
      DB_PASS: "${MYSQL_PASSWORD}"
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: eveilia-db
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
